"""Default component types and their inspection checklists."""

COMPONENT_TYPES = [
    "Shaft",
    "Gear",
    "Gearbox",
    "Coupling",
    "Hub",
    "Base",
    "Pulley",
    "Bearing Housing",
    "Roller",
    "Motor Component",
    "Pump Component",
    "Conveyor Component",
    "Custom Component",
]

DEFAULT_TEMPLATES: dict[str, list[str]] = {
    "Shaft": [
        "Visual condition",
        "Wear present",
        "Corrosion present",
        "Keyway condition",
        "Thread condition",
        "Straightness",
        "Journal condition",
        "Dimension verification",
        "Photos attached",
    ],
    "Gear": [
        "Visual condition",
        "Tooth wear",
        "Pitting / spalling",
        "Cracks present",
        "Bore condition",
        "Keyway condition",
        "Backlash check",
        "Dimension verification",
        "Photos attached",
    ],
    "Gearbox": [
        "External condition",
        "Oil condition / level",
        "Seal condition",
        "Bearing condition",
        "Gear set condition",
        "Housing integrity",
        "Input / output shaft condition",
        "Noise / backlash test",
        "Photos attached",
    ],
    "Coupling": [
        "Visual condition",
        "Element / insert wear",
        "Bore condition",
        "Keyway condition",
        "Alignment check",
        "Bolt / fastener condition",
        "Dimension verification",
        "Photos attached",
    ],
    "Hub": [
        "Visual condition",
        "Bore condition",
        "Keyway condition",
        "Cracks present",
        "Wear present",
        "Dimension verification",
        "Photos attached",
    ],
    "Base": [
        "Visual condition",
        "Cracks present",
        "Corrosion present",
        "Flatness check",
        "Mounting hole condition",
        "Weld integrity",
        "Photos attached",
    ],
    "Pulley": [
        "Visual condition",
        "Groove wear",
        "Bore condition",
        "Keyway condition",
        "Balance check",
        "Crack inspection",
        "Dimension verification",
        "Photos attached",
    ],
    "Bearing Housing": [
        "Visual condition",
        "Bore condition / ovality",
        "Cracks present",
        "Seal seat condition",
        "Mounting face condition",
        "Dimension verification",
        "Photos attached",
    ],
    "Roller": [
        "Visual condition",
        "Surface wear",
        "Bearing condition",
        "Shaft condition",
        "Concentricity check",
        "Dimension verification",
        "Photos attached",
    ],
    "Motor Component": [
        "Visual condition",
        "Winding condition",
        "Bearing condition",
        "Shaft condition",
        "Insulation resistance",
        "Terminal box condition",
        "Photos attached",
    ],
    "Pump Component": [
        "Visual condition",
        "Impeller condition",
        "Seal condition",
        "Shaft condition",
        "Wear ring clearance",
        "Casing condition",
        "Photos attached",
    ],
    "Conveyor Component": [
        "Visual condition",
        "Wear present",
        "Bearing condition",
        "Frame integrity",
        "Belt / chain condition",
        "Alignment check",
        "Photos attached",
    ],
    "Custom Component": [
        "Visual condition",
        "Wear present",
        "Corrosion present",
        "Dimension verification",
        "Photos attached",
    ],
}

JOB_STATUSES = [
    "Received",
    "Machining",
    "Inspection",
    "Inspection Failed",
    "Completed",
    "Awaiting Customer Review",
    "Closed",
]


# ---- NCR (Non-Conformance Report) option lists ----
NCR_CATEGORIES = [
    "Dimensional",
    "Material",
    "Workmanship",
    "Process",
    "Documentation",
    "Damage",
    "Other",
]
NCR_SEVERITIES = ["Minor", "Major", "Critical"]
NCR_SOURCES = [
    "Incoming",
    "In-Process",
    "Final Inspection",
    "Customer",
    "Supplier",
    "Other",
]
NCR_DISPOSITIONS = [
    "Pending",
    "Use As Is",
    "Rework",
    "Repair",
    "Scrap",
    "Return to Supplier",
]
NCR_STATUSES = ["Open", "In Progress", "Closed"]
